version: '3.9'
services:
  raiko:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        UBUNTU_IMAGE: ubuntu:22.04
        UBUNTU_CODENAME: jammy
    image: raiko:latest
    container_name: raiko
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - /data/log/sgx:/data/log/sgx
